version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: pingsanto-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined

  grafana:
    image: grafana/grafana:10.4.3
    container_name: pingsanto-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
